#include "stdafx.h"
#include "Engine.h"
#include <assert.h>
#include "ModuleUtils.h"
#include <stdio.h>

#define ADDRESS_WORLD 0x2913820 // ArmA-> - 400000
#define ADDRESS_NETWORKMANAGER 0x28D1A48 // ArmA-> - 400000 

//World 
#define OFFSET_WORLD_OBJECTSTABLE 0x11C8 
#define OFFSET_WORLD_REALPLAYER 0x26A8 
#define OFFSET_WORLD_PLAYERON 0x26A0 
#define OFFSET_WORLD_CAMERAON 0x2670 
#define OFFSET_WORLD_CAMERA 0x7E0 

//Network
#define OFFSET_NETWORKCLIENT 0x48 
#define OFFSET_NETWORKCLIENT_SCOREBOARD 0x38 
#define OFFSET_NETWORKCLIENT_PLAYERIDENTITY_SIZE 0x288 
#define OFFSET_NETWORKCLIENT_PLAYERIDENTITY_NETWORKID 0x8 
#define OFFSET_NETWORKCLIENT_PLAYERIDENTITY_PLAYERNAME 0x170 

//Cursor
#define OFFSET_WORLD_INGAMEUI 0x23C 

//LocalPlayer
#define OFFSET_PLAYER_VISUALSTATE 0xD0

//Entity
#define OFFSET_ENTITY_ENTITYTYPE 0x150 
#define OFFSET_ENTITY_FUTUREVISUALSTATE 0xD0 
#define OFFSET_ENTITY_RENDERERVISUALSTATE 0x190
#define OFFSET_ENTITY_ISDEAD 0x534 
#define OFFSET_ENTITY_SIDE 0x340 
#define OFFSET_ENTITY_NETWORKID 0xBBC 

//Entity Type
#define OFFSET_ENTITYTYPE_CLASSNAME 0x68 
#define OFFSET_ENTITYTYPE_CONFIGNAME 0xD0 
#define OFFSET_ENTITYTYPE_FUELLIMIT 0xAD0 
#define OFFSET_ENTITYTYPE_CLEANNAME 0x11F0 

#define OFFSET_VISUALSTATE_POSITION 0x2C 
#define OFFSET_VISUALSTATE_HEADPOSITION 0x168 
#define OFFSET_VISUALSTATE_CHESTPOSITION 0x174 

#define OFFSET_CAMERA_VIEWRIGHT 0x8 
#define OFFSET_CAMERA_VIEWUP 0x14 
#define OFFSET_CAMERA_VIEFORWARD 0x20 
#define OFFSET_CAMERA_VIEWTRANSLATION 0x2C 
#define OFFSET_CAMERA_VIEWPORTSIZE 0x58 
#define OFFSET_CAMERA_PROJECTION_D1 0xD0 

Engine::Engine()
{
	clientDll = (DWORD)GetModuleHandleW(L"client.dll");
	clientDllSize = ModuleUtils::GetModuleSize("client.dll");
	assert(clientDll);
	printf("[ENGINE] Modules initialized");
}
